-- Add up migration script here
CREATE TABLE IF NOT EXISTS jokes(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
author TEXT NOT NULL,
value TEXT NOT NULL,
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL);
